server:
  port: 9004

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ag_auth?useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    healthcheck:
      enabled: true

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

mybatis:
    basepackage: com.gibbons.auth.entity
    mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    com.gibbons.auth.mapper: debug

jwt:
  token-header: Authorization
  expire: 3600
  pri-key:
    path: ../gibbons-project/common-server/src/main/resources/jwt/pri.key
  pub-key:
    path: ../gibbons-project/common-server/src/main/resources/jwt/pub.key

client:
  expire: 3600
  pri-key:
    path: ../gibbons-project/common-server/src/main/resources/client/pri.key
  pub-key:
    path: ../gibbons-project/common-server/src/main/resources/client/pub.key